### ISSUE TITLE
Assess Bookdown -> Leanpub conversion needs

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/DaSL_Course_Template_Leanpub#26]
@carriewright11 started some work on this here for converting videos and embedded files to Leanpub friendly formats: 
https://github.com/jhudsl/ITCR_Cancer_Research_Leadership_LeanPub/tree/main/scripts

Questions to be assessed: 

1) How are these scripts working and should they be included here (with added documentation on how to use them)?
2) What conversion use cases should also be addressed in this template repo that aren't yet being addressed?
3) How should conversion happen? (manually or via github actions?) -- I'm inclined to have it happen automatically. 
4) What about when conversion fails? How should that be handled?

We should keep in mind when is it appropriate to write a conversion function versus when is better to be more prescriptive about how items should be linked/embedded in getting_started.md? More functions means more things that will need to be maintained -- not ideal. But too complicated of instructions in getting_started.md is also not super friendly to ourselves and other future authors.

**Comment by cansavvy** [comment]
Alright now that we have a working leanbuild + docker image combo, I'm going to start tackling this again.

**Comment by carriewright11** [comment]
I actually functionalized the video script... working on adding a testing repo for this

**Comment by cansavvy** [comment]
Awesome! I'd be happy to review what you've been working on! (And I'll send you PRs as I make progress too).

**Comment by carriewright11** [comment]
sounds great!

**Comment by carriewright11** [comment]
Here is the testing repo: https://github.com/jhudsl/testing_leanbuild_functions

The video function could be improved but it runs!  I put the raw leanbuild code here so we can test putting it together.

I think we should maybe require a standard way of adding videos, images etc. that way it is easier for us to tell people what to do and to maintain conversion functions. It gives people less flexibility of course but I think it might be less overwhelming to have one way to do everything. What do you think?

**Comment by carriewright11** [comment]
I can work on the embedded files script now if you want to work on polishing/putting things together from the video script

**Comment by cansavvy** [comment]
Yes I think having a standard approach for people to add things is better than having to maintain functions! 

I was thinking since you have more familiarity with where things need to go in leanbuild and have made some progress on that already; I will get the checking functions and github actions associated with that ready to go: https://github.com/jhudsl/DaSL_Course_Template_Leanpub/issues/24
What do you think? 

If we have the check-script going then that might help us with these functions you are setting up. Feed two birds with one scone so to speak. 

But I think reviewing/testing each other's code here via PR review will be critical for this stuff because this is the stuff that's going to be used by every course that's made from the template.

**Comment by cansavvy** [comment]
> I can work on the embedded files script now if you want to work on polishing/putting things together from the video script

I thoroughly enjoy being a polisher so this sounds good to me.

**Comment by carriewright11** [comment]
OK great - I think I will leave the code to work with html in case people still don't read our directions. I will update the template though to have one way of including images, videos, embedded files etc.

**Comment by cansavvy** [comment]
>  I think I will leave the code to work with html in case people still don't read our directions. 

Right no need to delete the code in case we want to come back to it, let's just not mention that that's an option in the `getting_started.md`. Would you be able to updated the `getting_started.md` with what people should be doing in this respect? (I'm not sure at this point).

**Comment by carriewright11** [comment]
> Right no need to delete the code in case we want to come back to it, let's just not mention that that's an option in the `getting_started.md`. Would you be able to updated the `getting_started.md` with what people should be doing in this respect? (I'm not sure at this point).

yup exactly what I was thinking :) - Yes, I can do that

**Comment by carriewright11** [comment]
> I was thinking since you have more familiarity with where things need to go in leanbuild and have made some progress on that already; I will get the checking functions and github actions associated with that ready to go: #24
> What do you think?

sounds good - I'll be focusing on getting the embedded files script functionalized. We can talk about splitting the functions even further etc. after you get a chance to look at them

**Comment by carriewright11** [comment]
OK I finished the first draft of these... you can copy the function scripts (with the same names (build_leanpub_embed_files.R and build_leanpub_video.R) in the R dir) to get the functions and currently you can try running:

library(here)
library(stringr)
update_embed() - you should see new Rmd files with "embed_ready" and the _bookdown.yml file should be updated

For video updates first need to run leanbuild::bookdown_to_leanpub()...
update_video()- you should see new md files in the manuscript directory with "leanpub_ready" and the book.txt file should be updated

Once we have modified everything the way that we like, then I can add these functions to the bookdown_to_leanpub.R code so that the leanbuild::bookdown_to_leanpub() function calls these functions (if we want to- which I think seems like the easiest option) and then all you will need to do is run leanbuild::bookdown_to_leanpub() to do all conversions. Perhaps we can do a git action about this so this get's run whenever a transfer pull request is merged.

**Comment by carriewright11** [comment]
I think the only thing left for the user would be to create the quizzes and add them to the book.txt file in the manuscript directory. Even if they don't though, the still appear in the course, there just isn't an extra reminder to take them in the chapter that they correspond to. Not the worst but not ideal. So maybe we can automate this later.

**Comment by cansavvy** [comment]
I think this issue has served its purpose and can close because more specific issues are tracking what is left. Like #14
