### ISSUE TITLE
Adding coursera files here

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/DaSL_Course_Template_Leanpub#40]
Regarding this issue:https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/156 

Add modified _output.yml code to create version without TOC for Coursera. This would also be the repo for the coursera quizzes.
Maybe retitle for hosted_courses instead of just LeanPub or something.

**Comment by cansavvy** [comment]
This has been done!
