### ISSUE TITLE
Create Coursera quizzes in a more automated way

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/DaSL_Course_Template_Leanpub#41]
Instead of just using the GUI, looks like you can use a few formats: https://partners.coursera.help/hc/en-us/articles/360057235331 
The YAML template would probably be the easier conversion to automate, but actually the docx one is the most similar to the Markua version. So maybe we should consider that option too.

**Comment by cansavvy** [comment]
This has been accomplished! Yay.
